// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/forhadulislam/go-swagger-api/models"
)

// GetV1UsersOKCode is the HTTP code returned for type GetV1UsersOK
const GetV1UsersOKCode int = 200

/*GetV1UsersOK Users fetched successfully

swagger:response getV1UsersOK
*/
type GetV1UsersOK struct {

	/*
	  In: Body
	*/
	Payload models.Users `json:"body,omitempty"`
}

// NewGetV1UsersOK creates GetV1UsersOK with default headers values
func NewGetV1UsersOK() *GetV1UsersOK {

	return &GetV1UsersOK{}
}

// WithPayload adds the payload to the get v1 users o k response
func (o *GetV1UsersOK) WithPayload(payload models.Users) *GetV1UsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 users o k response
func (o *GetV1UsersOK) SetPayload(payload models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1UsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Users{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetV1UsersInternalServerErrorCode is the HTTP code returned for type GetV1UsersInternalServerError
const GetV1UsersInternalServerErrorCode int = 500

/*GetV1UsersInternalServerError Error while fetching all user ids

swagger:response getV1UsersInternalServerError
*/
type GetV1UsersInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Status `json:"body,omitempty"`
}

// NewGetV1UsersInternalServerError creates GetV1UsersInternalServerError with default headers values
func NewGetV1UsersInternalServerError() *GetV1UsersInternalServerError {

	return &GetV1UsersInternalServerError{}
}

// WithPayload adds the payload to the get v1 users internal server error response
func (o *GetV1UsersInternalServerError) WithPayload(payload *models.Status) *GetV1UsersInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get v1 users internal server error response
func (o *GetV1UsersInternalServerError) SetPayload(payload *models.Status) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetV1UsersInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
