// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi GO Swagger API
A simple API built with Swagger for demonstration


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
