// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// UserID User ID of the created user
// swagger:model userId
type UserID string

// Validate validates this user Id
func (m UserID) Validate(formats strfmt.Registry) error {
	return nil
}
